# Generated by Django 5.0.2 on 2024-03-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='post_status',
            new_name='community_post_status',
        ),
    ]
